version: '3.7'
services:
#  auth:
#    container_name: auth
#    image: auth
#    build: .
#    ports:
#      - 8082:8082
#    depends_on:
#      - auth_db
  auth_db:
    container_name: auth-db
    image: postgres
    restart: on-failure
    ports:
      - 5002:5432
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth

#networks:
#  habit-tracker-backend:
#    external:
#        name: habit-tracker-backend
