version: '3.7'
services:
  notification:
    networks:
      - habit-tracker-backend
    container_name: notification
    image: notification
    build: .
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    networks:
      - habit-tracker-backend
networks:
  habit-tracker-backend:
    name: habit-tracker-backend