habit:
  property:
    delimiter: _
spring:
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 3600000
  datasource:
    url: jdbc:postgresql://localhost:5001/habitdb
    username: habit
    password: habit
  liquibase:
    change-log: classpath:db/database_changelog.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
server:
  port: 8081