habit:
  property:
    delimiter: _
spring:
  datasource:
    url: jdbc:postgresql://habit_db:5432/habitdb
    username: habit
    password: habit
  liquibase:
    change-log: classpath:db/database_changelog.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081