version: '3.7'
services:
  habit:
    networks:
      - habit-tracker-backend
    container_name: habit
    image: habit
    build: .
    depends_on:
      - habit_db
      - redis
  habit_db:
    container_name: habit-db
    image: postgres
    restart: on-failure
    networks:
      - habit-tracker-backend
    environment:
      POSTGRES_DB: habitdb
      POSTGRES_USER: habit
      POSTGRES_PASSWORD: habit
  redis:
    container_name: redis
    image: "redis:alpine"
    networks:
      - habit-tracker-backend

networks:
  habit-tracker-backend:
    name: habit-tracker-backend
