spring:
  datasource:
    url: jdbc:postgresql://localhost:5002/authdb
    username: auth
    password: auth
  liquibase:
    change-log: classpath:db/database_changelog.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082